export const BookingErrors = [
  {translation: 'no_errors', code: 0, message: 'no-error'},
  {translation: 'empty_input_data', code: -1, message: '<data> is empty'},
  {translation: 'empty_booking_start_date', code: -2, message: '<startAt> is empty'},
  {translation: 'empty_booking_end_date', code: -3, message: '<endAt> is empty'},
  {translation: 'empty_booking_status', code: -4, message: '<status> is empty'},
  {translation: 'invalid_booking_status', code: -5, message: '<status> is invalid'},
  {translation: 'blank_complex', code: -6, message: '<complex> is empty'},
  {translation: 'invalid_complex', code: -7, message: '<complex> is invalid'},
  {translation: 'field_empty', code: -8, message: '<field> is empty'},
  {translation: 'invalid_field', code: -9, message: '<field> is invalid'},
  {translation: 'empty_booker', code: -10, message: '<booker> is undefined'},
  {translation: 'already_used_slot', code: -11, message: '<slot> already used'},
  {translation: 'unauthorized_to_update_complex', code: -12, message: 'Unauthorized to update complex'},
  {translation: 'unauthorized_to_update_booker_infos', code: -13, message: 'Unauthorized to update booker infos'},
  {translation: 'unauthorized_to_accept_booking', code: -14, message: 'Unauthorized to accept this booking'},
  {translation: 'unauthorized_to_refuse_booking', code: -15, message: 'Unauthorized to refuse this booking'},
  {translation: 'booking_not_exist', code: -16, message: '<booking> not exists'},
  {translation: 'invalid_id', code: -17, message: '<id> is invalid'},
  {translation: 'invalid_target_model', code: -18, message: '<targetModel> is invalid'},
  {translation: 'impossible_to_change_field', code: -19, message: 'Impossible to update field of an other sport'},
  {translation: 'complex_previously_defined_invalid', code: -20, message: '<complex> previously defined is now invalid'},
  {translation: 'start_range_invalid', code: -21, message: '<startRange> is invalid'},
  {translation: 'closed_booking_access_forbidden', code: -22, message: 'Unauthorized to access to closed booking'},
  {translation: 'dates_cant_be_null', code: -23, message: '<startAt> or <endAt> can\'t be null'},
  {translation: 'endAt_cant_be_before_startAt', code: -24, message: '<endAt> can\'t be before <startAt>'},
  {translation: 'target_sport_invalid', code: -25, message: '<sport> is invalid for target'},
  {translation: 'target_doesnt_exist', code: -26, message: '<target> doesn\'t exist'},
  {translation: 'booking_settings_undefined', code: -998, message: 'Internal error - booking settings undefined'},
  {translation: 'internal_error', code: -999, message: 'Internal error'},
];
